### ISSUE TITLE
Extreme Lag - Lots of Lines Of Code

### ISSUE THREAD

**Issue by adamrpostjr** [iyonaga/minimap-lens#27]
When working with thousands of lines of code there is massive lag that is caused by lens. 

I have been noticing extreme lag that past few days while working with nearly 4000 lines of code.  A lot of this code was wrapping it self as well due to the lines being long. 

By extreme lag I mean atom stops responding until lens can catch up. 

Example: on line 20XX i need to move my mouse over to the other screen to work on the other screen and this would cause my mouse to pass over the minimap warranting the lens to pop up. This causes atom to lock up for about 30s to 60s.

**Comment by aminya** [comment]
@adamrpostjr This is something I tried so hard to fix. Despite all the optimizations I made in #31 #30 #29 #28 #24 #23 #21 #20 #19 #18 and #17, in very large files minimap lens blocks the main thread and prevents Atom to function properly. This is the limitation of [`appendChild`](https://github.com/iyonaga/minimap-lens/blob/5cb03d093d06bea3865536a307270bb8090f3750/lib/minimap-lens.js#L301) in JavaScript. It blocks the main thread and there is no way to use multi-threading here (as it is doing DOM manipulation).

I made a pull request in #32 to fix this.
