### ISSUE TITLE
Lens doesn't show what is under cursor

### ISSUE THREAD

**Issue by nagyj2** [iyonaga/minimap-lens#3]
When I use lens, the cursor's position and the lens 'peek' don't line up. The peek is several lines below the cursor. This makes it very disorienting to use.

**Comment by BenLeggiero** [comment]
I'm getting the same behavior. Kinda makes the lens useless.

**Comment by aviatesk** [comment]
These issues are going to be addressed and hopefully fixed in #4 ;)
